#localhost database
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=password

# vercel database
spring.datasource.url=jdbc:postgresql://ep-cold-cherry-068503.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require
spring.datasource.username=default
spring.datasource.password=MJH47NWLBzIc
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


#server.port=9999
jwt_expire=99999999
jwt_secret=JWT_SECRET